// adverts.v1.json's own vectors, kept out of generate.ts because they are the one set here built on real cryptographic material rather than structural filler, and because generate.ts is already at this repo's own max-lines cap.
//
// A peer-advert's signature is the only thing tying a gossiped device-id to the device that owns it (spec/transport.cddl, wire-mesh#225), and two implementations that disagree by a single byte about what is signed will reject each other's every advert while each passes its own tests. Freezing the signing input alongside the wire bytes is what turns that disagreement into a failing vector rather than a field mystery. The construction below is written from the spec text, deliberately not imported from either implementation: a vector generated by the thing it is meant to check would prove nothing.
//
// Ed25519 rather than ES256 because its signatures are deterministic (RFC 8032): CI regenerates this file's output and diffs it against the committed copy, which an ECDSA signature's fresh per-signing nonce would fail on every run. The keys come from fixed seeds for the same reason.

import {
  createHash,
  createPrivateKey,
  createPublicKey,
  sign as nodeSign,
  type KeyObject,
} from "node:crypto";
import { cdeEncodeOptions, encode } from "cbor2";
import {
  hex,
  toWire,
  type AdvertVector,
  type JsonWire,
} from "@exadev/wire-mesh-conformance";

const ED25519_SEED_BYTE_LENGTH = 32;
const EDDSA = -8; // COSE algorithm identifier for pure Ed25519 (RFC 9053)
const LOW_BYTE_MASK = 0xff; // XOR operand keeping a corrupted byte within one octet
const SNAPSHOT_SECONDS = 1861833600; // an arbitrary fixed Unix-seconds instant, so regenerating reproduces the committed bytes

/** RFC 8410 section 7's PKCS#8 prefix for an Ed25519 private key, sitting ahead of the 32 raw seed bytes and encoding the version, the 1.3.101.112 algorithm identifier, and the octet-string wrapper around the seed. Node accepts no rawer form for an Ed25519 private key, so the seed is wrapped rather than imported directly. */
const PKCS8_ED25519_PREFIX = Buffer.from(
  "302e020100300506032b657004220420",
  "hex",
);

/** The domain-separation prefix from spec/transport.cddl: the ASCII context string followed by one zero byte. */
const PEER_ADVERT_SIGNING_CONTEXT = Buffer.from(
  "wire-mesh/peer-advert/v1\u0000",
  "utf8",
);

interface AdvertIdentity {
  privateKey: KeyObject;
  publicKeyBytes: Buffer;
  deviceHex: string;
}

/** Builds a reproducible Ed25519 identity from a fixed, clearly-synthetic seed. Never a real device key. */
function identityFromSeed(seedFillHex: string): AdvertIdentity {
  const privateKey = createPrivateKey({
    key: Buffer.concat([
      PKCS8_ED25519_PREFIX,
      Buffer.from(seedFillHex.repeat(ED25519_SEED_BYTE_LENGTH), "hex"),
    ]),
    format: "der",
    type: "pkcs8",
  });
  const publicJwk = createPublicKey(privateKey).export({ format: "jwk" });
  if (typeof publicJwk.x !== "string") {
    throw new Error("Ed25519 public JWK is missing its raw x coordinate");
  }
  const publicKeyBytes = Buffer.from(publicJwk.x, "base64url");
  return {
    privateKey,
    publicKeyBytes,
    deviceHex: createHash("sha256").update(publicKeyBytes).digest("hex"),
  };
}

const advertiser = identityFromSeed("7c");
/** A second real key, used only to sign an advert naming a device it does not derive: the wrong-key case, which self-certification catches before any signature work. */
const impostor = identityFromSeed("9d");

/** The advert's own entries minus `signature`, canonically encoded and prefixed: exactly what spec/transport.cddl defines as the signing input. */
function advertSigningInput(
  advert: Readonly<Record<string, JsonWire>>,
): Buffer {
  const content: Record<string, JsonWire> = {};
  for (const [key, value] of Object.entries(advert)) {
    if (key === "signature") {
      continue;
    }
    content[key] = value;
  }
  return Buffer.concat([
    PEER_ADVERT_SIGNING_CONTEXT,
    Buffer.from(encode(toWire(content), cdeEncodeOptions)),
  ]);
}

function wireHex(message: JsonWire): string {
  return Buffer.from(encode(toWire(message), cdeEncodeOptions)).toString("hex");
}

/**
 * Builds one advert vector, signing the content with `signer` and recording the verdict a conformant verifier must reach for it.
 *
 * `tamper` runs after signing, which is how the negative vectors are produced: the advert really was signed, and then something the signature covers was changed, exactly as a hostile relay or peer would do it.
 */
function advertVector(
  name: string,
  advert: Readonly<Record<string, JsonWire>>,
  options: Readonly<{
    signer: KeyObject;
    verifies: boolean;
    tamper?: (signed: Record<string, JsonWire>) => void;
  }>,
): AdvertVector {
  const signature = nodeSign(null, advertSigningInput(advert), options.signer);
  const signed: Record<string, JsonWire> = {
    ...advert,
    signature: hex(signature.toString("hex")),
  };
  options.tamper?.(signed);
  return {
    name,
    message: signed,
    wire_hex: wireHex(signed),
    signing_input_hex: advertSigningInput(signed).toString("hex"),
    verifies: options.verifies,
  };
}

const advertBase: Record<string, JsonWire> = {
  device: hex(advertiser.deviceHex),
  addresses: ["203.0.113.5:4433"],
  "snapshot-seconds": SNAPSHOT_SECONDS,
  "identity-key": {
    alg: EDDSA,
    "public-key": hex(advertiser.publicKeyBytes.toString("hex")),
  },
};

export const advertVectors: AdvertVector[] = [
  advertVector("peer_advert_v1_valid", advertBase, {
    signer: advertiser.privateKey,
    verifies: true,
  }),
  // The extension tail is inside the signing input, so an advert carrying one is still ordinarily valid; the negative case below is what proves the tail is actually covered.
  advertVector(
    "peer_advert_v1_valid_with_extension",
    { ...advertBase, "presence/status": "idle" },
    { signer: advertiser.privateKey, verifies: true },
  ),
  // A relay rewriting one extension value on an otherwise genuine advert: accepting this would let anything forwarding gossip edit the facts it carries.
  advertVector(
    "peer_advert_v1_tampered_extension",
    { ...advertBase, "presence/status": "idle" },
    {
      signer: advertiser.privateKey,
      verifies: false,
      tamper: (signed) => {
        signed["presence/status"] = "active";
      },
    },
  ),
  // An extension key added after signing, which the tail's openness would otherwise make free: a verifier that encoded only the fields it recognised would accept this.
  advertVector("peer_advert_v1_added_extension", advertBase, {
    signer: advertiser.privateKey,
    verifies: false,
    tamper: (signed) => {
      signed["room/hosted"] = ["general"];
    },
  }),
  // A genuine signature by a real key, over an advert naming somebody else's device: refused by self-certification, since sha256 of the embedded public-key is not the claimed device.
  advertVector(
    "peer_advert_v1_wrong_key_for_device",
    {
      ...advertBase,
      "identity-key": {
        alg: EDDSA,
        "public-key": hex(impostor.publicKeyBytes.toString("hex")),
      },
    },
    { signer: impostor.privateKey, verifies: false },
  ),
  // The signature's last byte flipped: the plainest failure, and the one a verifier that skipped the signature check entirely would still pass.
  advertVector("peer_advert_v1_bad_signature", advertBase, {
    signer: advertiser.privateKey,
    verifies: false,
    tamper: (signed) => {
      const signature = signed.signature;
      if (
        typeof signature !== "object" ||
        signature === null ||
        !("hex" in signature) ||
        typeof signature.hex !== "string"
      ) {
        throw new Error("signed advert is missing its signature marker");
      }
      const bytes = Buffer.from(signature.hex, "hex");
      const lastIndex = bytes.length - 1;
      const lastByte = bytes.at(lastIndex);
      if (lastByte === undefined) {
        throw new Error("signature has no bytes to corrupt");
      }
      bytes[lastIndex] = lastByte ^ LOW_BYTE_MASK;
      signed.signature = hex(bytes.toString("hex"));
    },
  }),
];
