import { defineConfig } from "tsdown";

// Every real module gets its own build entry rather than a re-exporting index.ts -- the barrel-policy lint rule requires importing straight from the module that owns each export. src/generated/protocol.ts is committed, machine-generated output (see generate.ts); it's built here like any other module (real code that needs to compile and bundle correctly) but excluded from eslint's own strict authored-code rules (see eslint.config.ts's ignores) since rules like no-use-before-define don't make sense for its z.lazy()-wrapped mutually-recursive schemas.
export default defineConfig({
  entry: [
    "src/generated/protocol.ts",
    "src/generated/runtime.ts",
    "src/ports/transport.ts",
    "src/ports/storage.ts",
    "src/ports/identity.ts",
    "src/ports/clock.ts",
    "src/domain/bulk.ts",
    "src/domain/capability-grant.ts",
    "src/domain/capability-request.ts",
    "src/domain/data-sync.ts",
    "src/domain/erasure-coding.ts",
    "src/domain/device-id.ts",
    "src/domain/grant-candidates.ts",
    "src/domain/group-key.ts",
    "src/domain/handshake.ts",
    "src/domain/notice-board.ts",
    "src/domain/mesh-session.ts",
    "src/domain/relay-hub.ts",
    "src/domain/relay-use-gate.ts",
    "src/domain/room.ts",
    "src/domain/room-path.ts",
    "src/domain/room-rekey.ts",
    "src/domain/room-token-verification.ts",
    "src/domain/shard-manifest.ts",
    "src/domain/tokens.ts",
    "src/domain/threshold-subject.ts",
    "src/domain/revocation-view.ts",
    "src/domain/webrtc-signaling.ts",
    "src/adapters/frame-codec.ts",
    "src/adapters/threshold-wasm.ts",
    "src/adapters/threshold-identity.ts",
    "src/adapters/tcp-transport.ts",
    "src/adapters/tls-transport.ts",
    "src/adapters/memory-storage.ts",
    "src/adapters/node-fs-storage.ts",
    "src/adapters/node-identity.ts",
    "src/adapters/system-clock.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  exports: true,
  attw: { profile: "node16" },
  clean: true,
  // wasm-dist/wire_mesh_threshold_wasm.js (threshold-wasm.ts's own import) is wasm-bindgen's generated CommonJS glue, which loads its .wasm binary via a `${__dirname}/...` path at its OWN call site. Bundling would inline that line into dist/adapters/threshold-wasm.{mjs,cjs}, where __dirname resolves to dist/adapters/ instead of wasm-dist/ -- and for the ESM output specifically, rolldown's CJS-interop shim does not define __dirname at all, breaking the import outright (confirmed: `node --input-type=module` against the bundled .mjs throws "__dirname is not defined"). Keeping the import external instead means it is resolved at its own real, unbundled path at runtime, identical in both src/ (before build) and dist/ (after build) layouts since wasm-dist/ sits two directories up from both src/adapters/ and dist/adapters/ alike -- package.json's own "files" field ships wasm-dist/ alongside dist/ in the published tarball for exactly this reason.
  external: [/\/wasm-dist\//],
});
